2019-11-06 18:17:50.755 parsl.dataflow.dflow:83 [DEBUG]  Starting DataFlowKernel with config
Config(
    app_cache=True, 
    checkpoint_files=None, 
    checkpoint_mode=None, 
    checkpoint_period=None, 
    data_management_max_threads=10, 
    executors=[ThreadPoolExecutor(
        label='threads', 
        managed=True, 
        max_threads=2, 
        storage_access=None, 
        thread_name_prefix='', 
        working_dir=None
    )], 
    initialize_logging=True, 
    lazy_errors=True, 
    max_idletime=120.0, 
    monitoring=None, 
    retries=0, 
    run_dir='runinfo', 
    strategy='simple', 
    usage_tracking=False
)
2019-11-06 18:17:50.755 parsl.dataflow.dflow:84 [INFO]  Parsl version: 0.9.0
2019-11-06 18:17:50.756 parsl.dataflow.usage_tracking.usage:126 [DEBUG]  Tracking status: False
2019-11-06 18:17:50.756 parsl.dataflow.usage_tracking.usage:127 [DEBUG]  Testing mode   : False
2019-11-06 18:17:50.756 parsl.dataflow.dflow:110 [INFO]  Run id is: 8e114e26-25c7-47cf-b531-48e91897f6c4
2019-11-06 18:17:50.805 parsl.dataflow.memoization:52 [INFO]  App caching initialized
2019-11-06 18:17:50.806 parsl.dataflow.strategy:125 [DEBUG]  Scaling strategy: simple
2019-11-06 18:17:50.807 parsl.dataflow.dflow:484 [DEBUG]  Adding output dependencies
2019-11-06 18:17:50.807 parsl.dataflow.dflow:708 [INFO]  Task 0 submitted for App fun_1, waiting on tasks []
2019-11-06 18:17:50.807 parsl.dataflow.dflow:714 [DEBUG]  Task 0 set to pending state with AppFuture: <AppFuture super=<AppFuture at 0x7f1fc5da6048 state=pending>>
2019-11-06 18:17:50.807 parsl.dataflow.dflow:452 [INFO]  Task 0 launched on executor threads
2019-11-06 18:17:50.808 parsl.dataflow.dflow:288 [INFO]  Task 0 completed
2019-11-06 18:17:50.808 parsl.dataflow.dflow:484 [DEBUG]  Adding output dependencies
2019-11-06 18:17:50.808 parsl.dataflow.dflow:708 [INFO]  Task 1 submitted for App fun_1, waiting on tasks []
2019-11-06 18:17:50.808 parsl.dataflow.dflow:714 [DEBUG]  Task 1 set to pending state with AppFuture: <AppFuture super=<AppFuture at 0x7f1fc5da6550 state=pending>>
2019-11-06 18:17:50.808 parsl.dataflow.dflow:452 [INFO]  Task 1 launched on executor threads
2019-11-06 18:17:50.809 parsl.app.errors:158 [DEBUG]  Reraising exception of type <class 'TypeError'>
2019-11-06 18:17:50.809 parsl.dataflow.dflow:257 [DEBUG]  Task 1 failed
2019-11-06 18:17:50.809 parsl.dataflow.dflow:279 [ERROR]  Task 1 failed after 0 retry attempts
Traceback (most recent call last):
  File "/home/kalpani/.local/lib/python3.5/site-packages/parsl/dataflow/dflow.py", line 254, in handle_exec_update
    res.reraise()
  File "/home/kalpani/.local/lib/python3.5/site-packages/parsl/app/errors.py", line 163, in reraise
    reraise(t, v, tb)
  File "/home/kalpani/.local/lib/python3.5/site-packages/six.py", line 692, in reraise
    raise value.with_traceback(tb)
  File "/home/kalpani/.local/lib/python3.5/site-packages/parsl/app/errors.py", line 172, in wrapper
    return func(*args, **kwargs)
  File "thread.py", line 11, in fun_1
    return x*i
TypeError: unsupported operand type(s) for *: 'AppFuture' and 'int'
2019-11-06 18:17:50.809 parsl.app.errors:158 [DEBUG]  Reraising exception of type <class 'TypeError'>
2019-11-06 18:17:50.824 parsl.dataflow.dflow:864 [INFO]  DFK cleanup initiated
2019-11-06 18:17:50.824 parsl.dataflow.dflow:750 [INFO]  Summary of tasks in DFK:
2019-11-06 18:17:50.824 parsl.dataflow.dflow:781 [INFO]  Tasks in state States.done: 0
2019-11-06 18:17:50.824 parsl.dataflow.dflow:781 [INFO]  Tasks in state States.failed: 1
2019-11-06 18:17:50.824 parsl.dataflow.dflow:788 [INFO]  End of summary
2019-11-06 18:17:50.824 parsl.dataflow.dflow:888 [INFO]  Terminating flow_control and strategy threads
2019-11-06 18:17:50.824 parsl.executors.threads:96 [DEBUG]  Done with executor shutdown
2019-11-06 18:17:50.824 parsl.executors.threads:96 [DEBUG]  Done with executor shutdown
2019-11-06 18:17:50.825 parsl.dataflow.dflow:920 [INFO]  DFK cleanup complete
